### ISSUE TITLE
Expose resultBundlePath

### ISSUE THREAD

**Issue by ollitapa** [bitrise-io/steps-xcode-test#103]
Hi, 2.0.0 -> 2.1.0 started to change the default test-result path using "-resultBundlePath" option. Can you expose the path? Some of my CI-tools depend on an ".xcresult" file in that directory to be converted to JUNIT and in 2.1.0 I don't have the location anymore. Or is TestOutputDir already exposed?

The standard path is changed here:
https://github.com/bitrise-io/steps-xcode-test/blob/3f69dd1f610bd6ec8accbebb520362b47571ea07/main.go#L275

**Comment by lpusok** [comment]
Yes, I can do that.
You can also get junit rerort by setting the `xcpretty_test_options` option to:
```--color --report junit --output "${BITRISE_DEPLOY_DIR}/xcode-test-results-${BITRISE_SCHEME}.junit"```

**Comment by ollitapa** [comment]
Thanks, I've been using https://github.com/KrauseFx/trainer since it's sometimes a bit more reliable

**Comment by vanwagonet** [comment]
I'd also like an easier way to find the `.xcresult` path. Can that be an output environment variable?

**Comment by fehersanyi-bitrise** [comment]
Hy @vanwagonet, 
the tooling team already has a card on this, I think it will be made in the upcoming weeks 🙃

**Comment by BirmacherAkos** [comment]
Hi!

Today we will release a new version [2.2.0](https://github.com/bitrise-io/steps-xcode-test/releases/2.2.0) for the step which will export the .xcresult / resultBundlePath ( `BITRISE_XCRESULT_PATH` ).

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
