### ISSUE TITLE
Access the UI Test generated screenshots

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-xcode-test#12]
> `xcodebuild` test places them in the `derivedDataPath`

**Comment by bootstraponline** [comment]
:+1:

**Comment by godrei** [comment]
hi @bootstraponline 
we realesed a new version of the step (https://github.com/bitrise-io/steps-xcode-test/releases/tag/1.12.0).
From now you can use export_uitest_artifacts input to allow exporting the ui test artifacts (like screenshots) into BITRISE_DEPLOY_DIR.
