### ISSUE TITLE
Output of $BITRISE_XCODE_TEST_RESULT seems wrong - if there are no unit tests in the project

### ISSUE THREAD

**Issue by eugeneshih** [bitrise-io/steps-xcode-test#13]
If there are no unit tests, what should be the output? failed.

I happen to have a branch of code that has no unit tests and instead of the "succeeded" or "failed" output, a list of files.

**Comment by viktorbenei** [comment]
So, my question would be @eugeneshih - why do you have a test step if you don't have anything to test? We don't really want to modify the outputs, as this is the direct output of `xcodebuild` (Xcode's command line interface). If it fails this step fails. If it does not fail, this step will not fail and the "RESULT" env will be set to `succeeded`.

Modifying this would mean that you would get different results if you would run the test from Xcode, and we strictly want to stick to Xcode's results/output.

**Comment by eugeneshih** [comment]
Okay. Sounds good.

**Comment by viktorbenei** [comment]
As always, thank you for the feedback @eugeneshih !
