### ISSUE TITLE
build for tvOS

### ISSUE THREAD

**Issue by toshi0383** [bitrise-io/steps-xcode-test#28]
For tvOS, we need to set destination as following.

```
-destination platform=tvOS Simulator,name=Apple TV 1080p,OS=latest
```

**Comment by viktorbenei** [comment]
Thanks for reporting, we'll publish a new version of this Step to allow the `platform` to be changed!

**Comment by viktorbenei** [comment]
Version `1.9.0` was just released - it now includes the required Simulator Platform input, which can now be set to `tvOS` to test your tvOS apps. Release notes: https://github.com/bitrise-io/steps-xcode-test/releases/tag/1.9.0

Thank you for reporting the issue!

**Comment by toshi0383** [comment]
🎉
