### ISSUE TITLE
Expose the raw output as a build artifact, at least for failed builds or in a compressed form

### ISSUE THREAD

**Issue by jberkel** [bitrise-io/steps-xcode-test#30]
> tests fail with exit status 65, no diagnostic output

I ended up replacing the step with a simple shell script. 

```
▸ Touching motiTests.xctest
2016/02/10 05:10:41 Exporting: BITRISE_XCODE_TEST_RESULT
2016/02/10 05:10:41 Exporting: BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH
2016/02/10 05:10:41 xcode test failed with error: exit status 65
exit status 65
ERRO[05:10:41] Step (Xcode: Unit Test) failed, error: (exit status 1) 
```

**Comment by viktorbenei** [comment]
You could also switch the `output_tool` to `xcodebuild` - that'll log the full, raw output of Xcode, instead of the `xcpretty` formatted one.

Btw what was the issue in your case?

**Comment by jberkel** [comment]
Don't know, since I didn't see any output. And switching to xcodebuild just to check errors is not very convenient.

**Comment by viktorbenei** [comment]
The raw output is also exported into a file, which can be accessed at `$BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH` (you can see this in the logs). I agree that this is not the best solution, but this is not a Bitrise issue, it's an `xcpretty` bug/issue. In some cases `xcpretty` omits the error lines.

If you have a suggestion for a better solution please let us know! So far we could not find any.

**Comment by jberkel** [comment]
Ok, fair enough, but don't think the raw logs exposed as build artifacts? This would make post-failure debugging very easy.

**Comment by viktorbenei** [comment]
Hm... That might work. I guess we should only expose it if the build fails anyway.

The issue with the raw log is that usually `xcpretty` outputs the correct error and you don't need the huge raw logs (it's above 1MB for even a fairly simple project), but it might still be better to include it for every failed build, even if you see the nice, formatted error (output of `xcpretty`).

**Comment by jberkel** [comment]
Even keeping logs of successful builds might be useful (being able to see exact compiler flags for a specific build etc.) and compressed they should not take up too much space.

**Comment by viktorbenei** [comment]
I'll re-open this ticket and change the title, thanks for the feedback!

**Comment by viktorbenei** [comment]
@godrei please schedule this

**Comment by godrei** [comment]
Hi @jberkel,
we decided to keep raw logs only if xcodebuild fails.
We released a new version (https://github.com/bitrise-io/steps-xcode-test/releases/tag/1.12.0). From now the step will export the raw xcodebuild output log into BITRISE_DEPLOY_DIR as a compressed ZIP file.
Thanks for the feedback!

**Comment by jberkel** [comment]
@godrei great, thanks!
