### ISSUE TITLE
[Resolved] Xcode Unit Test step fails with exit code 66

### ISSUE THREAD

**Issue by bitwit** [bitrise-io/steps-xcode-test#32]
Mainly posting this as an FYI to others who might have the same issue. Hopefully this helps save someone else time.

The xcode scheme we use for CI/Production builds had no test target(s) so the test step would fail without any provided reason.

We added our test target to the scheme, pushed to remote and all was good.

**Comment by viktorbenei** [comment]
Thanks @bitwit , really appreciated!

Indeed, it seems that `xcpretty` sometimes omits these errors from the log, which obviously makes it quite hard to debug, unless you print the full `xcodebuild` output (which is quite huge and verbose).

We already have plans to find or write an alternative to `xcpretty`, to solve these issues.

**Comment by hclviv** [comment]
Dear @viktorbenei 

I am getting the same issue during running Bitrise CLI command on my local mac machine, Her is my log:

+------------------------------------------------------------------------------+
| (6) xcode-test@1.18.5                                                        |
+------------------------------------------------------------------------------+
| id: xcode-test                                                               |
| version: 1.18.5                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-07-12T17:58:11+05:30                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[17:58:11]  * [OK] Step dependency (xcode) installed, available. 
INFO[17:58:11]  * [OK] Step dependency (go) installed, available. 

Project Parameters:
- ProjectPath: DevOpsIntegration/DevOpsIntegration.xcworkspace
- Scheme: DevOpsIntegration

Simulator Configs:
- SimulatorPlatform: iOS Simulator
- SimulatorDevice: iPhone 6s Plus
- SimulatorOsVersion: latest

Test Run Configs:
- OutputTool: xcpretty
- IsCleanBuild: no
- IsSingleBuild: true
- ShouldBuildBeforeTest: yes
- ShouldRetryTestOnFail: no
- GenerateCodeCoverageFiles: no
- ExportUITestArtifacts: true
- TestOptions: 
- XcprettyTestOptions: --color --report html --output "/var/folders/yf/wfbtv79d30lbdt2s_mjdq1mw0000gq/T/deploy580893780/xcode-test-results-DevOpsIntegration.html"
- WaitForSimulatorBoot: yes

Other Configs:
* action: -workspace
* device_destination: platform=iOS Simulator,name=iPhone 6s Plus,OS=latest
* xcodebuild_version: Xcode 8.3.2 (Build version 8E2002)
* xcpretty_version: 0.2.8
* simulator_name: iPhone 6s Plus, UDID: 5B5B0F4F-1A7D-47E9-A84D-58FE7D53C643, status: Shutdown

Booting simulator (5B5B0F4F-1A7D-47E9-A84D-58FE7D53C643)...
$ open "/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app" "--args" "-CurrentDeviceUDID" "5B5B0F4F-1A7D-47E9-A84D-58FE7D53C643"
Waiting for simulator boot
...........................................................

Running the tests...
$ set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild "-workspace" "DevOpsIntegration/DevOpsIntegration.xcworkspace" "-scheme" "DevOpsIntegration" "build" "test" "-destination" "platform=iOS Simulator,name=iPhone 6s Plus,OS=latest" | xcpretty "--color" "--report" "html" "--output" "/var/folders/yf/wfbtv79d30lbdt2s_mjdq1mw0000gq/T/deploy580893780/xcode-test-results-DevOpsIntegration.html"

Failed to export UI test artifacts, error no test logs found at: /Users/viveksrivastav/Library/Developer/Xcode/DerivedData/DevOpsIntegration-fhqsyirtrooyswewdmbjuqsimpun
xcode test exit code: 66
xcode test failed, error: exit status 66
If you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path
is available in the $BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH environment variable.

You can check the full, unfiltered and unformatted Xcode output in the file: 
/var/folders/yf/wfbtv79d30lbdt2s_mjdq1mw0000gq/T/deploy580893780/raw-xcodebuild-output.log 
If you have the Deploy to Bitrise.io step (after this step), 
that will attach the file to your build as an artifact!
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-test@1.18.5 (exit code: 1)                              | 64 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-xcode-test/issues         |
| Source: https://github.com/bitrise-io/steps-xcode-test                       |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
@hclviv please see the content of the `raw-xcodebuild-output.log` file - it's at the path printed in the log (`You can check the full, unfiltered and unformatted Xcode output in the file ...`).

If that wouldn't help please copy paste it's content here.

**Comment by hclviv** [comment]
Hi @viktorbenei  - I checked log file and its shows "xcodebuild: error: 'DevOpsIntegration/DevOpsIntegration.xcworkspace' does not exist." I am not sure why this error is coming as file is there at location.

Any thought ??

**Comment by viktorbenei** [comment]
Without more info it's hard to say @hclviv ; the error comes from Xcode so I'd say you're probably not in the right directory when you run the command, maybe one dir up or down.

If you downloaded the `bitrise.yml` from bitrise.io please make sure to save it into the **root of your repository** and run it from there; relative paths are configured on bitrise.io to be relative to the root of the repo.

**Comment by hclviv** [comment]
Thanks @viktorbenei  your hint worked for me. 

I need your help to understand, how I can trigger bitbucket changes automatically using CLI running locally

**Comment by viktorbenei** [comment]
For generic Q&A please use https://discuss.bitrise.io @hclviv as this question is not related to this issue / to this step :)

**Comment by hclviv** [comment]
Thanks for the suggestion @viktorbenei

**Comment by alacsistemas** [comment]
> We added our test target to the scheme, pushed to remote and all was good.

How do you do that? I'm a newbie

**Comment by KevinVladG** [comment]
> > We added our test target to the scheme, pushed to remote and all was good.
> 
> How do you do that? I'm a newbie
what this video on how to make a UITest in Xcode once it's added to the scheme your action should work. It's what I did when I got the error code and it fixed it.

[](https://www.youtube.com/watch?v=rmKbsQ41wVY)
