### ISSUE TITLE
Support for Infer ?

### ISSUE THREAD

**Issue by mackoj** [bitrise-io/steps-xcode-test#39]
Hi do you plan to support [Infer](http://fbinfer.com) ?
I think the best way to support it is in this step.

[Collaboration with Spotify](http://fbinfer.com/blog/2016/03/17/collaboration-with-spotify.html) 
[Moving Fast with Software Verification](https://research.facebook.com/publications/moving-fast-with-software-verification/)

Cheers,

**Comment by viktorbenei** [comment]
Infer is a stand alone tool, so it should be a separate Step.

This step (`xcode-test`) runs Xcode's "test" command. Any tool which connects to it automatically will be run automatically. Any other tool which is not invoked by Xcode's "test" command should run separately, with a separate step.

Feel free to add this to https://github.com/bitrise-io/bitrise-contrib or create a related step ;)
