### ISSUE TITLE
Add option to configure derived data directory

### ISSUE THREAD

**Issue by andrewtheis** [bitrise-io/steps-xcode-test#40]
Currently a temporary directory for Xcode derived data is generated by the main.go script. However this is not exported as an output variable or configurable as an input option. We have another bitrise step (codecov) that is dependent on using the default derived data location (or you can use the Script step and define the location manually). Since steps-xcode-test does not expose the derived data path it generates we can't manually set this in our codecov step.

The steps-xcode-test step should export out the derived data directory path and/or allow the derived data directory path to be configured manually. This is the only way we can access the generated code coverage files in subsequent steps.

**Comment by viktorbenei** [comment]
Hi, 

The issue is, we would like to **not** change the DerivedData path if possible. 

Do you know a reliable way to determine the location of DerivedData if you don't pass in a path as a param to `xcodebuild`? 

The only reason we do this right now is to be able to get the Xcode UI test generated files (screenshots).

**Comment by andrewtheis** [comment]
@viktorbenei I've created a pull request that just dumps out the derived data directory as an environment variable at the end, so it can be used in subsequent steps rather than allowing it to be set. This allows subsequent steps to use the content in there.

**Comment by viktorbenei** [comment]
Sure, thanks, if we can't find any solution to not to override the DerivedData path we'll use that to share it with other steps - thanks you very much for the PR!! - but if there's any way to not to override the path we'd choose that solution instead.

**Comment by andrewtheis** [comment]
Step has been updated by dev team to use standard DerivedData location. Closed this issue.
