### ISSUE TITLE
Build command runs twice unnecessarily, doubling build times

### ISSUE THREAD

**Issue by andrewtheis** [bitrise-io/steps-xcode-test#45]
Currently the build is being made twice unnecessarily which doubles build time.

First this is run:
`xcodebuild "-workspace" "..." "-scheme" "..." "clean" "build" "-destination" "platform=iOS Simulator,name=iPhone 6s,OS=latest"`

Which cleans and builds the app (or if clean option is disabled, just builds the app).

Then this is run: 
`xcodebuild "-workspace" "..." "-scheme" "..." "build" "test" "-destination" "platform=iOS Simulator,name=iPhone 6s,OS=latest" 
`

Which builds the app a second time, for testing. Running with `build` uses a different config from the scheme than when `build` `test` are used together.

The first xcodebuild step can be removed to reduce build times by 50%. Or it should only run with the `clean` option and not `build`, if clean build has been enabled.

**Comment by viktorbenei** [comment]
The clean option is only applied on the first build, and not on the second one. The second one should be a minimal build, as that can use the first one's intermediate files. 

Do you have data about how much it would improve the performance if we'd skip the first build? In our tests the difference wasn't really significant. The double build solved an issue with a previous xcode version, as well as it reduces the log output, as the first build's output is only presented if it fails.

**Comment by andrewtheis** [comment]
Most projects use a different Build Config in their scheme for `build` than they do for `test`. So the first xcodebuild intermediate files aren't even used because it has to compile all over again. Right now Bitrise hangs on the first build step for ~400 seconds (with no output), than spends another ~400 seconds to make the build again for testing.

**Comment by viktorbenei** [comment]
that's a good call, we'll add an option to use the mode you want to, e.g. if the double build solves an Xcode issue. 

We'll most likely set the default to single build, to help speed up things. 

Thank you for the request!

**Comment by godrei** [comment]
New version (1.13.6)[https://github.com/bitrise-io/steps-xcode-test/releases/tag/1.13.6] got a new input `single_build `. If single_build: true, then step calls only xcodebuild OPTIONS build test OPTIONS, otherwise step runs xcodebuild OPTIONS build OPTIONS befor the test.

**Comment by viktorbenei** [comment]
1.13.6 is published into the StepLib - thanks again @andrewtheis for the suggestion!
