### ISSUE TITLE
Option to automatically try to run tests again when they fail

### ISSUE THREAD

**Issue by dagio** [bitrise-io/steps-xcode-test#54]
It would nice to have an option to try to run the test a second time when they fail. It would be useful for UI tests that are fragile. I wanted to add the option but I'm not confortable with Go

**Comment by viktorbenei** [comment]
I agree that something like this might be helpful, but on the other hand this would also mean that if you have an actual failing test that would double your test times..

**Comment by dagio** [comment]
Yes I agree it's far from perfect. That's why it should be an option disabled by default and everyone should choose depending of his project. In our case we are wasting time over failing builds for random reasons (thanks Xcode...) so we need to look for some solutions. If we do it well we would not recompile but just, run again the test. That would save quite some time.

**Comment by viktorbenei** [comment]
indeed, I guess if this is an opt-in option instead of an opt-out one that can be useful in some use cases

we'll try to schedule this ASAP, although we're a bit busy right now.. new Trigger Map handling and such ;)

**Comment by godrei** [comment]
Hi @dagio ,
[version 1.15.](https://github.com/bitrise-io/steps-xcode-test/releases) got a new input: `should_retry_test_on_fail `, you can use this to retry the test if it fails.

Thanks for the issue!

**Comment by dagio** [comment]
Thanks to you ! I will git it a try
