### ISSUE TITLE
Compilation performed twice

### ISSUE THREAD

**Issue by bclausdorff** [bitrise-io/steps-xcode-test#55]
**Problem**
Calling `xcodebuild test ...` does trigger a compilation before performing the tests on its own.
Calling `xcodebuild build test ...` leads to the code being compiled twice before performing the tests. The second compilation might be unnecessary and have a negative impact on the duration.

**Proposal**
- [ ] Drop the `build` argument from the command, because the `test` action does compile the code before testing anyway.

**Local experiment**
The following observations took place on my computer with the same commandline options (-project, -scheme, -destination) as on bitrise and cleaning before every build. I called xcodebuild from the commandline:

| abbreviated command           | result                  | duration |
|-------------------------------|--------------------------|----------|
| xcodebuild test ...       | 1x compilation + 1x test | 4:47 min |
| xcodebuild build test ... | 2x compilation + 1x test | 6:58 min |

All tests were performed without problem calling only `xcodebuild test ...`

**Local config**
- Xcode 7.3.1 + El Capitan

**Bitrise Xcode Test Step config**
- Xcode 7.3.1 + El Capitan
- `single_build: true`
- `clean_build: false`

**Extract from the bitrise logfile**
```
...
Building Project/Project [Debug]
Check Dependencies
Running script 'SwiftLint'
Compiling AddNewViewController.swift
...
Touching ProjectTests.xctest
Build Succeeded
Building Project/Project [Debug]
Check Dependencies
Running script 'SwiftLint'
Compiling AddNewViewController.swift
...
Touching ProjectTests.xctest
Building Project/ProjectUITests [Debug]
Check Dependencies
Processing Info.plist
Preprocessing /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents/XCTRunner.app/Info.plist
Compiling UITestCase.swift
Linking ProjectUITests
Touching ProjectUITests.xctest
All tests
Quick.framework
Test Suite ProjectTests.xctest started
...
```

**Comment by viktorbenei** [comment]
`build` is included in the `xcodebuild` command because previous Xcode versions did have bugs which appeared if on a branch new machine, where you never compiled the project before, you only ran `xcodebuild test` it timed out or otherwise misbehaved.

But I guess, if we implement this in an opt-in way that should be fine.

Thanks for the feature request and for the details!
