### ISSUE TITLE
Timeout: Build took more than 2700 seconds

### ISSUE THREAD

**Issue by dagio** [bitrise-io/steps-xcode-test#57]
Today we are experiencing many build failing because of this timeout. It happens during the Xcode run test step.

It stopped at : `Touching MyAppTests.xctest`

**Comment by dagio** [comment]
Without `xcpretty` I managed to get more information : 

```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to erase contents and settings in current state: Booted
```

I will remove the pre-action that I have that was cleaning the simulator and try again : 

```
# Reset simulator
xcrun simctl erase all
```

**Comment by viktorbenei** [comment]
Did it work once you removed the pre action?

**Comment by dagio** [comment]
Yes it does

**Comment by viktorbenei** [comment]
Wow, so if you do a `xcrun simctl erase all` it can cause Xcode to hang?? That's one more things to add to our https://bitrise-io.github.io/devcenter/ios/known-xcode-issues/ ...

**Comment by viktorbenei** [comment]
Thanks for reporting and for the infos/details! ;)

**Comment by dagio** [comment]
My guess is the test pre action is happening after xcode already start the simulator and do some stuffs. Trying to reset the simulator settings here does not seems to be a good idea because it will mess things up.

**Comment by viktorbenei** [comment]
I agree, but this still shouldn't cause it to hang ;)
Kinda makes sense, but it should print an error instead
