### ISSUE TITLE
xcode-test@1.14.1 (exit code: 1)

### ISSUE THREAD

**Issue by jw84** [bitrise-io/steps-xcode-test#63]
![image](https://cloud.githubusercontent.com/assets/48764/18895547/62d93fac-84cf-11e6-9852-367761bcf07c.png)

Is this my issue or is the build being blocked because the dependency isn't up to date?

**Comment by viktorbenei** [comment]
Without the rest of the step's logs it's impossible to say

**Comment by viktorbenei** [comment]
In general, you sums upgrade the step to the latest version though

**Comment by jw84** [comment]
Figured out bitrise's dashboard and updated! Still 65 error, now troubleshooting! Thanks @viktorbenei

**Comment by viktorbenei** [comment]
No problem - let us know if you'd need any help (but don't forget to include the full step log ;) )
