### ISSUE TITLE
Is it possible to only build (not build & test) a scheme?

### ISSUE THREAD

**Issue by akashivskyy** [bitrise-io/steps-xcode-test#74]
Is it possible to only **build** a scheme, without running the tests, in case a target doesn't have any?

**Comment by viktorbenei** [comment]
If you don't want to run tests, nor generate an app from the project, only build it, you should use the **
Xcode Analyze** step, which runs Xcode's Analyze command on the project.

I'll close this issue for tracking purposes, but if you have any questions just let us know here or on https://discuss.bitrise.io
