### ISSUE TITLE
Early unexpected exit, operation never finished bootstrapping

### ISSUE THREAD

**Issue by Landan** [bitrise-io/steps-xcode-test#76]
`Running script '[CP] Copy Pods Resources'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Touching UITests.xctest
▸ Signing /Users/vagrant/Library/Developer/Xcode/DerivedData/Project-gtlsyysavgzqejcwgxuiyrbtqmah/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/UITests-Runner.app/PlugIns/UITests.xctest

xcodebuild[3246:15026] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}`

Happens quite often only on Bitrise, cannot reproduce it locally with the same xcode and simulator versions.

**Comment by viktorbenei** [comment]
Hi,

Can you please contact us through the onsite chat instead, with the build URL? We'll need some additional logs/infos for this.
