### ISSUE TITLE
Xcode Test step fails when starting tests

### ISSUE THREAD

**Issue by ryango** [bitrise-io/steps-xcode-test#80]
Does not repro locally on matching Xcode and macOS versions
Xcode 9 (9A235)
macOS 10.12.6 (16G29)

seems like simulators aren't booting in time for tests or something. Reached out to support but logging here as well.

Automatic retry reason found in log: Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
isAutomaticRetryOnReason=false, no more retry, stopping the test!
xcode test exit code: 65
xcode test failed, error: exit status 65
If you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log

**Comment by ryango** [comment]
I have all retries on in debug

**Comment by viktorbenei** [comment]
Hi @ryango ,

Can you please follow this local repro guide https://discuss.bitrise.io/t/how-to-debug-your-build-locally-it-works-on-my-mac-pc-but-not-on-bitrise-io/392 and let us know how it goes?

If that doesn't help, please include the whole build log here or send it to our support via email or the onsite chat and we'll look into it ASAP! :)

**Comment by ryango** [comment]
Just ran with bitrise CLI from my yml and succeeded locally. Maybe issue with simulators? I hear this issue is cropping up on CI machines. Working with on site support chat now.

**Comment by viktorbenei** [comment]
@ryango did you follow the guide step by step? Eg did you start with a fresh clone of the repository? Also, did you reset the simulator?

**Comment by ryango** [comment]
Completely clean directory, 
brew install bitrise
saved my yaml to my directory
set env vars
bitrise run CI

this does a completely fresh clone of the repository, completely fresh carthage build
local simulator was fresh but is probably the variable

related to these:
https://discuss.bitrise.io/t/xcode-9-build-twice/2825/4?u=godreikrisztian
https://github.com/fastlane/fastlane/issues/6968

Was using fastlane but per Krisztian, swiched to using the xcode test step and it still fails after retrying, though has started to succeed more frequently recently

**Comment by viktorbenei** [comment]
Thanks for the infos @ryango !

You mentioned that you also contacted our support via email / the onsite chat support. I'll go ahead and close the issue here, so that all infos are at a single place (available for support directly), but feel free to point support to this thread for infos (if you did not share the same there).

**Comment by ctews** [comment]
Sorry for reopening that issue, but any updates on that? We are facing this problem extremely often! :(

**Comment by viktorbenei** [comment]
Hi @ctews please create an issue report at https://discuss.bitrise.io/c/issues/build-issues and we'll check it asap! 

Thanks! 😊
