### ISSUE TITLE
Need help in pointing to Workspace file

### ISSUE THREAD

**Issue by Abdul-Hannan** [bitrise-io/steps-xcode-test#90]
Hello, I have modified our project structure and after that, Xcode test step is no more able to find Workspace file. Basically, we have moved everything inside a folder named `ios`

**Previous settings:**

Environment variable Workspace paths resolves to : App.xcworkspace

<img width="1038" alt="screen shot 2018-06-24 at 11 26 23 am" src="https://user-images.githubusercontent.com/7346169/41816915-cbf8f484-77a1-11e8-8202-7bdb77be76ad.png">
<img width="1067" alt="screen shot 2018-06-24 at 11 27 30 am" src="https://user-images.githubusercontent.com/7346169/41816916-cc2e2622-77a1-11e8-991b-5fdafa6b0739.png">

**New settings:**

- I have just changed path the workspace as `ios/app.xcworkspace`.
- Also I have changed $BITRISE_SOURCE_DIR to `$BITRISE_SOURCE_DIR/ios `

Xcode test steps fails saying can not file the workspace file

**Comment by Abdul-Hannan** [comment]
closing this as I had a typo in my path

**Comment by viktorbenei** [comment]
Thanks for reporting @Abdul-Hannan and glad to hear you found the solution! :)
