### ISSUE TITLE
Copy of screenshots in Xcode 10 seems to be failing

### ISSUE THREAD

**Issue by mikemee** [bitrise-io/steps-xcode-test#95]
When I get a test failure, which triggers copying of screenshots, I get this error in my log:

```
Exporting attachments
Failed to export UI test artifacts, error no test attachments found at: /Users/vagrant/Library/Developer/Xcode/DerivedData/LogicPuzzles-gewhzekhsopbesfofqckztpeajlv/Logs/Test/Attachments
xcode test exit code: 65
```

Digging around a bit on my local machine, it seems the screenshots generated by Xcode (against a physical device) are being generated into here:
```
/Users/mikemee/Library/Developer/Xcode/DerivedData/LogicPuzzles-chwfavjcvixfrmglqiyrkkxrorxb/Logs/Test/Test-LogicPuzzles-2018.09.19_21-26-52-+0800.xcresult/1_Test/Attachments
```
When I ran it on a simulator, I found it in this folder (i.e. the same except the timestamp in the directory name):
```
/Users/mikemee/Library/Developer/Xcode/DerivedData/LogicPuzzles-chwfavjcvixfrmglqiyrkkxrorxb/Logs/Test/Test-LogicPuzzles-2018.09.19_21-37-49-+0800.xcresult/1_Test/Attachments
```

I'm guessing this new location is needed because multiple simulators may run at the same time.  

Hopefully you're aware of this and working on it, but if not... here it is!

**Comment by bitce** [comment]
Hi @mikemee , I've replied on discuss as well but please send us a build URL or log file in any of these threads, or ping us on our on-site chat with this issue so we are able to look into it in depth!

**Comment by mikemee** [comment]
@bitce Great!  I replied on discuss.  LMK if you need more info, but I expect you can reproduce it with any iOS build that has the "copy screenshots to assets" (whatever it's called??)  option changed from the default of false to true.

**Comment by godrei** [comment]
Hi @mikemee,
thanks for the report, the fix is scheduled.

**Comment by BirmacherAkos** [comment]
Hi @mikemee !

We will release a fix today [(v1.18.17)](https://github.com/bitrise-io/steps-xcode-test/releases/tag/1.18.17) for this issue. 
Could you please wire in the new version and try again?

**Comment by mikemee** [comment]
@BirmacherAkos thanks!  I auto-run the latest version of `xcode-test`, and it _seemed_ to work differently today, but I still can't see the screenshots in the output archives. Perhaps some of my other settings are wrong (I never used this feature before Xcode 10).  Here's a link to the build: https://app.bitrise.io/build/e6c7009b53d040de

**Comment by BirmacherAkos** [comment]
Thanks for the response @mikemee !
And thanks again for the detailed issue report :D

I'm closing the issue.
Happy Building! 🚀
